--- #YAML:1.0
name:                Getopt-Mixed
version:             1.10
abstract:            getopt processing with both long and short options
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Christopher J. Madsen <perl@cjmweb.net>
